version: '3.9'
services:
    postgres:
        image: postgres:16
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - postgres_net

volumes:
    postgres_data:


networks:
    postgres_net:
        external: true
