version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: postgres_teste
        environment:
            POSTGRES_USER: meuuser
            POSTGRES_PASSWORD: minhasenha
            POSTGRES_DB: meuteste
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
